apiVersion: v1
entries:
  meshery:
  - apiVersion: v2
    appVersion: latest
    created: "2020-02-10T11:33:45.373694+08:00"
    dependencies:
    - condition: mesheryistio.enabled
      name: mesheryistio
      repository: ""
      version: 0.1.0
    - condition: mesherylinkerd.enabled
      name: mesherylinkerd
      repository: ""
      version: 0.1.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: 65fa90d72355425b85c0299a711b652afb6e7f8f8b856b3c939883f049f60740
    icon: https://github.com/layer5io/meshery/blob/master/ui/static/img/meshery-logo/meshery-logo.svg
    keywords:
    - meshery
    - mesheryistio
    - mesherylinkerd
    maintainers:
    - email: urakiny@gmail.com
      name: aisuko
    name: meshery
    type: application
    urls:
    - https://meshery.io/charts/meshery-0.1.0.tgz
    version: 0.1.0
generated: "2020-02-10T11:33:45.368352+08:00"
