apiVersion: v1
entries:
  meshery:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-01-22T15:38:25.542089437+08:00"
    dependencies:
    - condition: meshery-istio.enabled
      name: meshery-istio
      repository: ""
      version: 2.0.1
    - condition: meshery-linkerd.enabled
      name: meshery-linkerd
      repository: ""
      version: 2.0.1
    - condition: meshery-consul.enabled
      name: meshery-consul
      repository: ""
      version: 2.0.1
    - condition: meshery-kuma.enabled
      name: meshery-kuma
      repository: ""
      version: 1.0.1
    - condition: meshery-osm.enabled
      name: meshery-osm
      repository: ""
      version: 1.0.1
    - condition: meshery-nsm.enabled
      name: meshery-nsm
      repository: ""
      version: 1.0.1
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: b4894fce4d7e648292941f58d77254e6e5a6d0b41b7b2bdd9eedb65b950aa385
    icon: https://meshery.io/images/logos/meshery-logo.png
    keywords:
    - meshery
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-kuma
    - meshery-osm
    - meshery-nsm
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery
    type: application
    urls:
    - meshery-2.1.2.tgz
    version: 2.1.2
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-01-22T15:38:25.538683401+08:00"
    dependencies:
    - condition: meshery-istio.enabled
      name: meshery-istio
      repository: ""
      version: 2.0.1
    - condition: meshery-linkerd.enabled
      name: meshery-linkerd
      repository: ""
      version: 2.0.1
    - condition: meshery-consul.enabled
      name: meshery-consul
      repository: ""
      version: 2.0.1
    - condition: meshery-kuma.enabled
      name: meshery-kuma
      repository: ""
      version: 1.0.1
    - condition: meshery-osm.enabled
      name: meshery-osm
      repository: ""
      version: 1.0.1
    - condition: meshery-nsm.enabled
      name: meshery-nsm
      repository: ""
      version: 1.0.1
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: f77e549fecd5d7a8871007a68fbb7bbb59a7c831d956c88c36a8032bad95439b
    icon: https://meshery.io/images/logos/meshery-logo.png
    keywords:
    - meshery
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-kuma
    - meshery-osm
    - meshery-nsm
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery
    type: application
    urls:
    - meshery-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-01-22T15:38:25.535127039+08:00"
    dependencies:
    - condition: meshery-istio.enabled
      name: meshery-istio
      repository: ""
      version: 2.0.0
    - condition: meshery-linkerd.enabled
      name: meshery-linkerd
      repository: ""
      version: 2.0.0
    - condition: meshery-consul.enabled
      name: meshery-consul
      repository: ""
      version: 2.0.0
    - condition: meshery-kuma.enabled
      name: meshery-kuma
      repository: ""
      version: 1.0.0
    - condition: meshery-osm.enabled
      name: meshery-osm
      repository: ""
      version: 1.0.0
    - condition: meshery-nsm.enabled
      name: meshery-nsm
      repository: ""
      version: 1.0.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: 06172a0d81a2c59a1d549e535849ecf022d735f26b1bb6580be1e2d5134e321d
    icon: https://meshery.io/images/logos/meshery-logo.png
    keywords:
    - meshery
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-kuma
    - meshery-osm
    - meshery-nsm
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery
    type: application
    urls:
    - meshery-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-01-22T15:38:25.530634491+08:00"
    dependencies:
    - condition: meshery-istio.enabled
      name: meshery-istio
      repository: ""
      version: 2.0.0
    - condition: meshery-linkerd.enabled
      name: meshery-linkerd
      repository: ""
      version: 2.0.0
    - condition: meshery-consul.enabled
      name: meshery-consul
      repository: ""
      version: 2.0.0
    - condition: meshery-kuma.enabled
      name: meshery-kuma
      repository: ""
      version: 1.0.0
    - condition: meshery-osm.enabled
      name: meshery-osm
      repository: ""
      version: 1.0.0
    - condition: meshery-nsm.enabled
      name: meshery-nsm
      repository: ""
      version: 1.0.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: 3a569164991675cafa1c537cd7cac17f04ee8f84bf45213cf3b76c88406c2208
    icon: https://meshery.io/images/logos/meshery-logo.png
    keywords:
    - meshery
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-kuma
    - meshery-osm
    - meshery-nsm
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery
    type: application
    urls:
    - meshery-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    created: "2021-01-22T15:38:25.52715823+08:00"
    dependencies:
    - condition: mesheryistio.enabled
      name: mesheryistio
      repository: ""
      version: 0.1.0
    - condition: mesherylinkerd.enabled
      name: mesherylinkerd
      repository: ""
      version: 0.1.0
    - condition: mesheryconsul.enabled
      name: mesheryconsul
      repository: ""
      version: 0.1.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: bdeb78916694c5ef2a24c62cfc83b1789b29ce7b335bcf431b3975eb90072aee
    icon: https://github.com/layer5io/meshery/blob/master/ui/public/static/img/meshery-logo/meshery-logo.svg
    keywords:
    - meshery
    - mesheryistio
    - mesherylinkerd
    - mesheryconsul
    maintainers:
    - email: urakiny@gmail.com
      name: aisuko
    name: meshery
    type: application
    urls:
    - meshery-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: latest
    created: "2021-01-22T15:38:25.524900967+08:00"
    dependencies:
    - condition: mesheryistio.enabled
      name: mesheryistio
      repository: ""
      version: 0.1.0
    - condition: mesherylinkerd.enabled
      name: mesherylinkerd
      repository: ""
      version: 0.1.0
    description: Meshery chart for deploying Meshery and Meshery's adapters.
    digest: 65fa90d72355425b85c0299a711b652afb6e7f8f8b856b3c939883f049f60740
    icon: https://github.com/layer5io/meshery/blob/master/ui/static/img/meshery-logo/meshery-logo.svg
    keywords:
    - meshery
    - mesheryistio
    - mesherylinkerd
    maintainers:
    - email: urakiny@gmail.com
      name: aisuko
    name: meshery
    type: application
    urls:
    - meshery-0.1.0.tgz
    version: 0.1.0
  meshery-consul:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-05-28T18:34:33.708123431Z"
    description: Meshery Adapter for Consul chart.
    digest: 4f52c28278c675a3c85264c1ad56f280f677cf5a1185b49242f35f377a76e6dc
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery-consul
    type: application
    urls:
    - https://layer5io.github.io/meshery.io/charts/meshery-consul-2.0.1.tgz
    version: 2.0.1
  meshery-istio:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-05-28T18:34:33.708822656Z"
    description: Meshery Adapter for Istio chart.
    digest: 656ec4da5d962772e0ad3bac4227422c1751dc379523bdc639808cd60cdfd9bf
    maintainers:
    - email: urakiny@gmail.com
      name: aisuko
    - email: leecalcote@gmail.com
      name: leecalcote
    name: meshery-istio
    type: application
    urls:
    - https://layer5io.github.io/meshery.io/charts/meshery-istio-2.0.1.tgz
    version: 2.0.1
  meshery-kuma:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-05-28T18:34:33.709438978Z"
    description: Meshery Adapter for Kuma.
    digest: 553b6d85f8910e88e01a45154befcf22ad750964a5e8b1e17cfe05e115fc78da
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery-kuma
    type: application
    urls:
    - https://layer5io.github.io/meshery.io/charts/meshery-kuma-1.0.1.tgz
    version: 1.0.1
  meshery-linkerd:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-05-28T18:34:33.710221205Z"
    description: Mesherylinkerd chart for deploying meshery-linkerd.
    digest: 3782a76025a6382a09d4258cfc40bb3bcd5b14200b712731203259e8e2beaf6d
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery-linkerd
    type: application
    urls:
    - https://layer5io.github.io/meshery.io/charts/meshery-linkerd-2.0.1.tgz
    version: 2.0.1
  meshery-nsm:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-05-28T18:34:33.710902329Z"
    description: Meshery Adapter for Network Service Mesh.
    digest: c6bada6f996291cca65de0ced6f08c7daa46c5a4442765ea848c3ad509a1b4ce
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery-nsm
    type: application
    urls:
    - https://layer5io.github.io/meshery.io/charts/meshery-nsm-1.0.1.tgz
    version: 1.0.1
  meshery-osm:
  - apiVersion: v2
    appVersion: stable-latest
    created: "2021-05-28T18:34:33.71205937Z"
    description: Meshery Adapter for Open Service Mesh
    digest: 566b8e24805a1912e1ded16c821eb007447cdc14e1d1155d66c41677af183332
    maintainers:
    - email: community@layer5.io
      name: Layer5 Authors
    - email: urakiny@gmail.com
      name: aisuko
    - email: lee.calcote@layer5.io
      name: leecalcote
    name: meshery-osm
    type: application
    urls:
    - https://layer5io.github.io/meshery.io/charts/meshery-osm-1.0.1.tgz
    version: 1.0.1
generated: "2021-05-28T18:34:33.7072566Z"
